[package]
name = "imageproc"
version = "0.20.0"
authors = ["theotherphil"]
edition = "2018"
license = "MIT"
description = "Image processing operations"
readme = "README.md"
repository = "https://github.com/image-rs/imageproc.git"
homepage = "https://github.com/image-rs/imageproc"
exclude = ["examples/*.ttf"]

[features]
default = []
property-testing = [ "quickcheck" ]
display-window = ["sdl2"]

[dependencies]
conv = "0.3.3"
image = { version = "0.23.0", default-features = false }
itertools = "0.8.2"
num = "0.2.1"
rand = "0.7.3"
rand_distr = "0.2.2"
rusttype = "0.8.2"
rayon = "1.3.0"
quickcheck = { version = "0.9.2", optional = true }
sdl2 = { version = "0.33.0", optional = true, default-features = false, features = ["bundled"] }
rulinalg = "0.4.2"

[dev-dependencies]
assert_approx_eq = "1.1.0"
image = "0.23.0"
quickcheck = "0.9.2"
wasm-bindgen-test = "0.3.8"

[package.metadata.docs.rs]
# See https://github.com/image-rs/imageproc/issues/358
# all-features = true
features = [ "property-testing" ]

[profile.release]
opt-level = 3
debug = true

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
